"""Tests for build-context to public-source binding."""

import io
import socket
import tarfile
from pathlib import Path

import pytest

import scripts.verify_source_revision as verifier
from scripts.verify_source_revision import compare_sources


def _write_source_tree(root: Path, *, app_value: str = "same") -> None:
    for relative in (
        "Dockerfile",
        "LICENSE",
        "NOTICE.md",
        "README.md",
        "pyproject.toml",
        "requirements.txt",
        "third-party-sources.json",
        "scripts/download_models.py",
        "scripts/verify_source_revision.py",
    ):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(relative, encoding="utf-8")
    (root / "app").mkdir()
    (root / "app/main.py").write_text(app_value, encoding="utf-8")


def test_compare_sources_accepts_identical_runtime_inputs(tmp_path):
    local = tmp_path / "local"
    public = tmp_path / "public"
    _write_source_tree(local)
    _write_source_tree(public)
    generated = local / "app/__pycache__/main.cpython-313.pyc"
    generated.parent.mkdir()
    generated.write_bytes(b"local generated bytecode")

    compare_sources(local, public)


def test_compare_sources_rejects_code_claiming_another_revision(tmp_path):
    local = tmp_path / "local"
    public = tmp_path / "public"
    _write_source_tree(local, app_value="modified runtime")
    _write_source_tree(public, app_value="public runtime")

    with pytest.raises(ValueError, match="app/main.py"):
        compare_sources(local, public)


def test_runtime_removes_generated_bytecode_before_execution():
    dockerfile = Path("Dockerfile").read_text(encoding="utf-8")
    dockerignore = Path(".dockerignore").read_text(encoding="utf-8")
    compose = Path("docker-compose.yml").read_text(encoding="utf-8")

    assert "-name __pycache__" in dockerfile
    assert "-name '*.pyc'" in dockerfile
    assert "PYTHONDONTWRITEBYTECODE=1" in dockerfile
    assert "**/__pycache__" in dockerignore
    assert "**/*.pyc" in dockerignore
    assert "./app:/app/app" not in compose
    assert "--reload" not in compose


def test_build_source_download_ignores_proxy_and_ca_environment(monkeypatch, tmp_path):
    class FakeResponse(io.BytesIO):
        status = 200

        def __init__(self):
            super().__init__(b"archive bytes")

    class FakeConnection:
        created = []

        def __init__(self, address, timeout):
            self.__class__.created.append((address, timeout))

        def request(self, method, path, headers):
            assert method == "GET"
            assert path == f"{verifier.CODELOAD_PATH}/{'a' * 40}"
            assert "User-Agent" in headers

        def getresponse(self):
            return FakeResponse()

        def close(self):
            return None

    def public_dns(_hostname, port, **_kwargs):
        return [(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP, "", ("8.8.8.8", port))]

    monkeypatch.setenv("HTTPS_PROXY", "http://127.0.0.1:7777")
    monkeypatch.setenv("SSL_CERT_FILE", "/nonexistent/hostile-ca.pem")
    monkeypatch.setenv("SSL_CERT_DIR", "/nonexistent/hostile-ca-directory")
    monkeypatch.setattr(verifier.socket, "getaddrinfo", public_dns)
    monkeypatch.setattr(verifier, "_PinnedHTTPSConnection", FakeConnection)

    destination = tmp_path / "source.tar.gz"
    verifier._download_archive("a" * 40, destination)

    assert destination.read_bytes() == b"archive bytes"
    assert FakeConnection.created == [("8.8.8.8", 60)]
    assert verifier._trusted_tls_context().get_ca_certs()


@pytest.mark.parametrize("address", ["127.0.0.1", "224.0.0.1", "ff02::1", "fec0::1"])
def test_build_source_download_rejects_non_public_dns(monkeypatch, address):
    family = socket.AF_INET6 if ":" in address else socket.AF_INET

    def unsafe_dns(_hostname, port, **_kwargs):
        return [(family, socket.SOCK_STREAM, socket.IPPROTO_TCP, "", (address, port))]

    monkeypatch.setattr(verifier.socket, "getaddrinfo", unsafe_dns)

    with pytest.raises(ValueError, match="non-public address"):
        verifier._resolve_codeload_addresses()


def test_build_source_download_rejects_redirect_without_reading_body(monkeypatch, tmp_path):
    class RedirectResponse(io.BytesIO):
        status = 302

        def __init__(self):
            super().__init__(b"")

        def read(self, *_args, **_kwargs):
            raise AssertionError("redirect body must not be read")

    class RedirectConnection:
        def __init__(self, *_args, **_kwargs):
            return None

        def request(self, *_args, **_kwargs):
            return None

        def getresponse(self):
            return RedirectResponse()

        def close(self):
            return None

    monkeypatch.setattr(verifier, "_resolve_codeload_addresses", lambda: ("8.8.8.8",))
    monkeypatch.setattr(verifier, "_PinnedHTTPSConnection", RedirectConnection)

    with pytest.raises(OSError, match="HTTP 302"):
        verifier._download_archive("a" * 40, tmp_path / "source.tar.gz")


def test_source_extraction_rejects_expansion_bomb(monkeypatch, tmp_path):
    archive_path = tmp_path / "source.tar.gz"
    payload = b"x" * 20
    member = tarfile.TarInfo("repo/app/large.py")
    member.size = len(payload)
    with tarfile.open(archive_path, mode="w:gz") as archive:
        archive.addfile(member, io.BytesIO(payload))
    monkeypatch.setattr(verifier, "MAX_EXTRACTED_SOURCE_BYTES", 10)

    with pytest.raises(ValueError, match="expanded size limit"):
        verifier._extract_archive(archive_path, tmp_path / "public")


def test_source_extraction_stops_before_materializing_too_many_members(monkeypatch, tmp_path):
    archive_path = tmp_path / "source.tar.gz"
    with tarfile.open(archive_path, mode="w:gz") as archive:
        archive.addfile(tarfile.TarInfo("repo/first"))
        archive.addfile(tarfile.TarInfo("repo/second"))
    monkeypatch.setattr(verifier, "MAX_ARCHIVE_MEMBERS", 1)

    with pytest.raises(ValueError, match="too many members"):
        verifier._extract_archive(archive_path, tmp_path / "public")
